# Generated by Django 4.1.2 on 2022-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nacimiento',
            new_name='fecha_creacion',
        ),
    ]
